### ISSUE TITLE
Wrong CppCheckPath condition in CppCheckTask.targets setting for x64 platform

### ISSUE THREAD

**Issue by Bertk** [SonarOpenCommunity/sonar-cxx-msbuild-tasks#21]
CppCheck is installed in **C:\Program Files\Cppcheck** on a Windows Server 2012 R2 system (PROCESSOR_ARCHITECTURE=AMD64) but the default configuration uses x86 only.

``` xml
<CppCheckPath               Condition="'$(CppCheckPath)' == ''">C:\Program Files (x86)\Cppcheck\cppcheck.exe</CppCheckPath>
```

**Comment by jmecosta** [comment]
hum, thats weird. i also have AMD64 and it lands in (x86) since the cppckeck is x86 build? 

this is my env. 
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=3c03
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files

if you let the cxx install it where does it land?

**Comment by Bertk** [comment]
There are two versions of CppCheck.exe 
- x64 - size 129 KB - 11/14/2015 7:23PM
- x86 - size 102 KB - 11/14/2015 7:13PM

They published the x64 after official release announcement and chocolateyInstall.ps1 supports 2 install packages:

```
$packageName = 'cppcheck' 
$installerType = 'MSI'
$url = 'http://sourceforge.net/projects/cppcheck/files/cppcheck/1.71/cppcheck-1.71-x86-Setup.msi' 
$urlX64 = 'http://sourceforge.net/projects/cppcheck/files/cppcheck/1.71/cppcheck-1.71-x64-Setup.msi' 
$silentArgs = '/quiet' 
$validExitCodes = @(0)

Install-ChocolateyPackage "$packageName" "$installerType" "$silentArgs" "$url" "$urlX64" -validExitCodes $validExitCodes
```

Which one did you use?

**Comment by Bertk** [comment]
Forgot to mention - CppCheck was installed by sonar-cxx-msbuild-tasks. I usually only copy the tools to build systems without running the installation.

**Comment by jmecosta** [comment]
I should have used the x86, so for the cxx runner it should pick up the exe
from the correct location.

For the nuget I am unsure if its useful to change those since they are
meant to be changed anyhow by specifying /p.

Or I could do a search inside the task, if not found in x86 search in the
other folder.

The installation was done by chocolatey so nothing outstanding there

**Comment by jmecosta** [comment]
should be handled in new release:
https://github.com/jmecsoftware/sonar-cxx-msbuild-tasks/releases/download/1.4/CxxSonarQubeMsbuidRunner.zip
